### ISSUE TITLE
Exits full screen when hovering over page buttons

### ISSUE THREAD

**Issue by wouterpeere** [tblanke/ScenarioGUI#67] opened 2023-06-29 15:49 UTC
Hi @tblanke 

I noticed some strange behaviour. When the number of pages is as high as your screen height (which is the case for this specific laptop), whenever you hover over a page button, the window exits full screen.

I changed the example document in this branch that illustrates my problem. If you don't notice the escape from the full screen, perhaps your screen is higher than mine and you need to add extra pages to see this bug.

Best,
@wouterpeere

**Comment by tblanke** [comment] 2023-06-30 06:29
Hi @wouterpeere ,

I think I have fixed the issue. Can you please take a look?

With best regards
@tblanke

**Comment by WouterEnead** [comment] 2023-06-30 06:58
Hi @tblanke 

The problem is indeed solved when hovering over the page buttons.
However, when you press calculate and the result page pops open, the window is still exitting full screen mode ...

Best regards,
@wouterpeere

**Comment by tblanke** [comment] 2023-06-30 07:35
Hi @WouterEnead 

I Think this should be now fixed as well.

With best regards
@tblanke

**Comment by wouterpeere** [comment] 2023-06-30 08:23
Hi @tblanke 

I confirm!

Best,
@wouterpeere

**Closed** 2023-06-30 13:50 UTC
Labels: bug
